# Generated by Django 5.1 on 2024-08-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonBlog', '0002_postmodel_auteur_postmodel_date_publication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postmodel',
            options={'ordering': ('-date_publication',)},
        ),
    ]
