# Generated by Django 5.1 on 2024-09-02 12:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MonBlog', '0004_commentaires'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentaires',
            new_name='Commentaire',
        ),
    ]
