# Generated by Django 5.1 on 2024-08-30 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='Profils', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])]),
        ),
    ]
